local M = {}
local api = vim.api

local conf_path = vim.fs.joinpath(vim.env.HOME, ".config", "kitty", "chameleon-theme.conf")

M.transparent = false
M.opacity = 0.85
M._saved_bg = {} -- original bg values per highlight group before going transparent

local transparent_groups = { "Normal", "NormalFloat", "NormalNC", "SignColumn", "FoldColumn" }

--- Extract a hex color from a highlight group attribute.
---@param group string
---@param attr "bg"|"fg"
---@return string|nil
local function hl_hex(group, attr)
	local hl = api.nvim_get_hl(0, { name = group, link = false })
	local val = hl[attr]
	if val then
		return string.format("#%06X", val)
	end
	return nil
end

--- Save current bg values for transparent_groups.
local function save_backgrounds()
	M._saved_bg = {}
	for _, group in ipairs(transparent_groups) do
		local hl = api.nvim_get_hl(0, { name = group, link = false })
		if hl.bg then
			M._saved_bg[group] = hl.bg
		end
	end
end

--- Clear bg on transparent_groups so Kitty shows through.
local function clear_backgrounds()
	for _, group in ipairs(transparent_groups) do
		local hl = api.nvim_get_hl(0, { name = group, link = false })
		hl.bg = nil
		hl.link = nil
		api.nvim_set_hl(0, group, hl)
	end
end

--- Restore saved bg values.
local function restore_backgrounds()
	for group, bg in pairs(M._saved_bg) do
		local hl = api.nvim_get_hl(0, { name = group, link = false })
		hl.bg = bg
		hl.link = nil
		api.nvim_set_hl(0, group, hl)
	end
end

--- Build a color map from the current Neovim colorscheme.
---@return table<string, string>
local function get_nvim_colors()
	local colors = {}

	colors.background = hl_hex("Normal", "bg")
		or hl_hex("NormalFloat", "bg")
		or hl_hex("NormalNC", "bg")
		or hl_hex("StatusLine", "bg")
	colors.foreground = hl_hex("Normal", "fg")
	colors.cursor = hl_hex("Cursor", "bg") or hl_hex("Normal", "fg")
	colors.cursor_text_color = hl_hex("Cursor", "fg") or hl_hex("Normal", "bg")
	colors.selection_background = hl_hex("Visual", "bg")
	colors.selection_foreground = hl_hex("Visual", "fg")

	local term_map = {
		[0] = { "Normal", "bg" },
		[1] = { "DiagnosticError", "fg" },
		[2] = { "DiagnosticOk", "fg" },
		[3] = { "DiagnosticWarn", "fg" },
		[4] = { "DiagnosticInfo", "fg" },
		[5] = { "Statement", "fg" },
		[6] = { "Special", "fg" },
		[7] = { "Normal", "fg" },
	}

	for i = 0, 7 do
		local term_hl = api.nvim_get_hl(0, { name = "Terminal" .. i, link = false })
		if term_hl.fg then
			colors["color" .. i] = string.format("#%06X", term_hl.fg)
		else
			local map = term_map[i]
			colors["color" .. i] = hl_hex(map[1], map[2])
		end

		local bright_hl = api.nvim_get_hl(0, { name = "Terminal" .. (i + 8), link = false })
		if bright_hl.fg then
			colors["color" .. (i + 8)] = string.format("#%06X", bright_hl.fg)
		else
			colors["color" .. (i + 8)] = colors["color" .. i]
		end
	end

	return colors
end

--- Search for a bundled Kitty theme file from the Neovim colorscheme plugin.
--- Looks in lazy plugin dirs under extras/kitty/ for a matching .conf file.
---@param name string colorscheme name (e.g. "tokyonight-day", "kanagawa")
---@return string|nil path to the .conf file, or nil
local function find_bundled_kitty_theme(name)
	local lazy_path = vim.fn.stdpath("data") .. "/lazy"
	-- Normalize: "tokyonight-day" → "tokyonight_day", "rose-pine" → "rose_pine"
	local normalized = name:gsub("-", "_")
	-- Also try without variant: "tokyonight_day" → search in tokyonight.nvim
	local base = normalized:match("^([^_]+)") or normalized

	-- Search patterns in priority order
	local candidates = {
		normalized .. ".conf",              -- exact: tokyonight_day.conf
		name:gsub("-", "_") .. ".conf",     -- same as above
		name .. ".conf",                    -- with dashes: tokyonight-day.conf
	}

	-- Find plugin dirs that might contain this theme
	local plugin_patterns = {
		base .. ".nvim",       -- tokyonight.nvim
		base .. "-nvim",       -- some-theme-nvim
		base,                  -- just the name
	}

	for _, plugin in ipairs(plugin_patterns) do
		local kitty_dir = lazy_path .. "/" .. plugin .. "/extras/kitty"
		for _, candidate in ipairs(candidates) do
			local path = kitty_dir .. "/" .. candidate
			local f = io.open(path, "r")
			if f then
				f:close()
				return path
			end
		end
		-- Also scan the directory for partial matches
		local handle = vim.uv.fs_scandir(kitty_dir)
		if handle then
			while true do
				local entry_name, entry_type = vim.uv.fs_scandir_next(handle)
				if not entry_name then break end
				if entry_type == "file" and entry_name:match("%.conf$") then
					-- Check if filename contains the normalized colorscheme name
					local entry_norm = entry_name:gsub("%.conf$", "")
					if entry_norm == normalized then
						return kitty_dir .. "/" .. entry_name
					end
				end
			end
		end
	end
	return nil
end

--- Write colors + opacity to the Kitty conf file.
local function write_kitty_conf()
	local cs_name = vim.g.colors_name or "default"

	local lines = {
		"# Auto-generated by Chameleon.nvim — do not edit",
		"# chameleon_colorscheme: " .. cs_name,
	}
	table.insert(lines, string.format("%-24s %s", "background_opacity", M.opacity))

	-- Try to use the bundled Kitty theme from the colorscheme plugin
	local bundled = find_bundled_kitty_theme(cs_name)
	if bundled then
		local bf = io.open(bundled, "r")
		if bf then
			for line in bf:lines() do
				-- Skip comments and empty lines from the bundled file
				if not line:match("^#") and not line:match("^%s*$") then
					table.insert(lines, line)
				end
			end
			bf:close()
		end
	else
		-- Fall back to extracting colors from Neovim highlight groups
		local colors
		if M.transparent and next(M._saved_bg) then
			colors = get_nvim_colors()
			if M._saved_bg.Normal then
				colors.background = string.format("#%06X", M._saved_bg.Normal)
			end
		else
			colors = get_nvim_colors()
		end

		for name, hex in pairs(colors) do
			if hex then
				table.insert(lines, string.format("%-24s %s", name, hex))
			end
		end
	end

	local f = io.open(conf_path, "w")
	if not f then
		vim.notify("Chameleon.nvim: Cannot write " .. conf_path, vim.log.levels.ERROR)
		return
	end
	f:write(table.concat(lines, "\n") .. "\n")
	f:close()
end

--- Read the saved colorscheme name from the conf file.
---@return string|nil
local function read_saved_colorscheme()
	local f = io.open(conf_path, "r")
	if not f then
		return nil
	end
	for line in f:lines() do
		local name = line:match("^# chameleon_colorscheme: (.+)")
		if name then
			f:close()
			return name
		end
	end
	f:close()
	return nil
end

--- Restore the colorscheme that was last synced to Kitty.
function M.restore()
	local name = read_saved_colorscheme()
	if name and name ~= vim.g.colors_name then
		vim.cmd.colorscheme(name)
		vim.notify("Restored: " .. name)
	elseif name then
		vim.notify("Already on " .. name)
	else
		vim.notify("No saved colorscheme found")
	end
end

--- Toggle transparency on/off.
function M.toggle_transparency()
	vim.schedule(function()
		if M.transparent then
			M.transparent = false
			M.opacity = 1.0
			restore_backgrounds()
		else
			M.transparent = true
			M.opacity = M._user_opacity or 0.85
			save_backgrounds()
			clear_backgrounds()
		end
		write_kitty_conf()
		vim.notify(
			M.transparent
				and string.format("Transparency ON (%.0f%%)", M.opacity * 100)
				or "Transparency OFF"
		)
	end)
end

--- Set opacity level (0.0 to 1.0). Enables transparency if not already on.
---@param level number
function M.set_opacity(level)
	vim.schedule(function()
		level = math.max(0.0, math.min(1.0, level))
		M._user_opacity = level
		M.opacity = level
		if not M.transparent then
			M.transparent = true
			save_backgrounds()
			clear_backgrounds()
		end
		write_kitty_conf()
		vim.notify(string.format("Opacity: %.0f%%", level * 100))
	end)
end

--- Increase opacity by step.
function M.increase_opacity()
	M.set_opacity((M.opacity or 0.85) + 0.05)
end

--- Decrease opacity by step.
function M.decrease_opacity()
	M.set_opacity((M.opacity or 0.85) - 0.05)
end

--- Sync on colorscheme change.
local function on_colorscheme()
	if M.transparent then
		save_backgrounds()
		clear_backgrounds()
	end
	write_kitty_conf()
end

local function setup_autocmds()
	local group = api.nvim_create_augroup("ChameleonSync", { clear = true })

	api.nvim_create_autocmd({ "ColorScheme", "VimResume", "VimEnter" }, {
		pattern = "*",
		callback = on_colorscheme,
		group = group,
	})
end

---@param opts? { opacity?: number, transparent?: boolean }
M.setup = function(opts)
	if not vim.env.KITTY_PID then
		return
	end
	opts = opts or {}
	if opts.opacity then
		M._user_opacity = opts.opacity
		M.opacity = opts.opacity
	end
	if opts.transparent then
		M.transparent = true
	end
	setup_autocmds()
end

return M
