local M = {}
local api = vim.api

local conf_path = vim.fs.joinpath(vim.env.HOME, ".config", "kitty", "chameleon-theme.conf")

M.transparent = false
M.opacity = 0.85
M._saved_bg = {} -- original bg values per highlight group before going transparent

local transparent_groups = { "Normal", "NormalFloat", "NormalNC", "SignColumn", "FoldColumn" }

--- Extract a hex color from a highlight group attribute.
---@param group string
---@param attr "bg"|"fg"
---@return string|nil
local function hl_hex(group, attr)
	local hl = api.nvim_get_hl(0, { name = group, link = false })
	local val = hl[attr]
	if val then
		return string.format("#%06X", val)
	end
	return nil
end

--- Save current bg values for transparent_groups.
local function save_backgrounds()
	M._saved_bg = {}
	for _, group in ipairs(transparent_groups) do
		local hl = api.nvim_get_hl(0, { name = group, link = false })
		if hl.bg then
			M._saved_bg[group] = hl.bg
		end
	end
end

--- Clear bg on transparent_groups so Kitty shows through.
local function clear_backgrounds()
	for _, group in ipairs(transparent_groups) do
		local hl = api.nvim_get_hl(0, { name = group, link = false })
		hl.bg = nil
		-- Remove link to avoid conflicts
		hl.link = nil
		api.nvim_set_hl(0, group, hl)
	end
end

--- Restore saved bg values.
local function restore_backgrounds()
	for group, bg in pairs(M._saved_bg) do
		local hl = api.nvim_get_hl(0, { name = group, link = false })
		hl.bg = bg
		hl.link = nil
		api.nvim_set_hl(0, group, hl)
	end
end

--- Build a color map from the current Neovim colorscheme.
---@return table<string, string>
local function get_nvim_colors()
	local colors = {}

	colors.background = hl_hex("Normal", "bg")
		or hl_hex("NormalFloat", "bg")
		or hl_hex("NormalNC", "bg")
		or hl_hex("StatusLine", "bg")
	colors.foreground = hl_hex("Normal", "fg")
	colors.cursor = hl_hex("Cursor", "bg") or hl_hex("Normal", "fg")
	colors.cursor_text_color = hl_hex("Cursor", "fg") or hl_hex("Normal", "bg")
	colors.selection_background = hl_hex("Visual", "bg")
	colors.selection_foreground = hl_hex("Visual", "fg")

	local term_map = {
		[0] = { "Normal", "bg" },
		[1] = { "DiagnosticError", "fg" },
		[2] = { "DiagnosticOk", "fg" },
		[3] = { "DiagnosticWarn", "fg" },
		[4] = { "DiagnosticInfo", "fg" },
		[5] = { "Statement", "fg" },
		[6] = { "Special", "fg" },
		[7] = { "Normal", "fg" },
	}

	for i = 0, 7 do
		local term_hl = api.nvim_get_hl(0, { name = "Terminal" .. i, link = false })
		if term_hl.fg then
			colors["color" .. i] = string.format("#%06X", term_hl.fg)
		else
			local map = term_map[i]
			colors["color" .. i] = hl_hex(map[1], map[2])
		end

		local bright_hl = api.nvim_get_hl(0, { name = "Terminal" .. (i + 8), link = false })
		if bright_hl.fg then
			colors["color" .. (i + 8)] = string.format("#%06X", bright_hl.fg)
		else
			colors["color" .. (i + 8)] = colors["color" .. i]
		end
	end

	return colors
end

--- Write colors + opacity to the Kitty conf file.
local function write_kitty_conf()
	local colors
	if M.transparent and next(M._saved_bg) then
		colors = get_nvim_colors()
		if M._saved_bg.Normal then
			colors.background = string.format("#%06X", M._saved_bg.Normal)
		end
	else
		colors = get_nvim_colors()
	end

	local lines = { "# Auto-generated by Chameleon.nvim — do not edit" }
	table.insert(lines, string.format("%-24s %s", "background_opacity", M.opacity))

	for name, hex in pairs(colors) do
		if hex then
			table.insert(lines, string.format("%-24s %s", name, hex))
		end
	end

	local f = io.open(conf_path, "w")
	if not f then
		vim.notify("Chameleon.nvim: Cannot write " .. conf_path, vim.log.levels.ERROR)
		return
	end
	f:write(table.concat(lines, "\n") .. "\n")
	f:close()
end

--- Toggle transparency on/off.
function M.toggle_transparency()
	vim.schedule(function()
		if M.transparent then
			M.transparent = false
			M.opacity = 1.0
			restore_backgrounds()
		else
			M.transparent = true
			M.opacity = M._user_opacity or 0.85
			save_backgrounds()
			clear_backgrounds()
		end
		write_kitty_conf()
		vim.notify(
			M.transparent
				and string.format("Transparency ON (%.0f%%)", M.opacity * 100)
				or "Transparency OFF"
		)
	end)
end

--- Set opacity level (0.0 to 1.0). Enables transparency if not already on.
---@param level number
function M.set_opacity(level)
	vim.schedule(function()
		level = math.max(0.0, math.min(1.0, level))
		M._user_opacity = level
		M.opacity = level
		if not M.transparent then
			M.transparent = true
			save_backgrounds()
			clear_backgrounds()
		end
		write_kitty_conf()
		vim.notify(string.format("Opacity: %.0f%%", level * 100))
	end)
end

--- Increase opacity by step.
function M.increase_opacity()
	M.set_opacity((M.opacity or 0.85) + 0.05)
end

--- Decrease opacity by step.
function M.decrease_opacity()
	M.set_opacity((M.opacity or 0.85) - 0.05)
end

--- Sync on colorscheme change.
local function on_colorscheme()
	if M.transparent then
		save_backgrounds()
		clear_backgrounds()
	end
	write_kitty_conf()
end

local function setup_autocmds()
	local group = api.nvim_create_augroup("ChameleonSync", { clear = true })

	api.nvim_create_autocmd({ "ColorScheme", "VimResume", "VimEnter" }, {
		pattern = "*",
		callback = on_colorscheme,
		group = group,
	})
end

---@param opts? { opacity?: number, transparent?: boolean }
M.setup = function(opts)
	if not vim.env.KITTY_PID then
		return
	end
	opts = opts or {}
	if opts.opacity then
		M._user_opacity = opts.opacity
		M.opacity = opts.opacity
	end
	if opts.transparent then
		M.transparent = true
	end
	setup_autocmds()
end

return M
