local M = {}
local api = vim.api

local conf_path = vim.fs.joinpath(vim.env.HOME, ".config", "kitty", "chameleon-theme.conf")

--- Extract a hex color from a highlight group attribute.
---@param group string
---@param attr "bg"|"fg"
---@return string|nil
local function hl_hex(group, attr)
	local hl = api.nvim_get_hl(0, { name = group, link = false })
	local val = hl[attr]
	if val then
		return string.format("#%06X", val)
	end
	return nil
end

--- Build a color map from the current Neovim colorscheme.
---@return table<string, string>
local function get_nvim_colors()
	local colors = {}

	colors.background = hl_hex("Normal", "bg")
	colors.foreground = hl_hex("Normal", "fg")
	colors.cursor = hl_hex("Cursor", "bg") or hl_hex("Normal", "fg")
	colors.cursor_text_color = hl_hex("Cursor", "fg") or hl_hex("Normal", "bg")
	colors.selection_background = hl_hex("Visual", "bg")
	colors.selection_foreground = hl_hex("Visual", "fg")

	local term_map = {
		[0] = { "Normal", "bg" },
		[1] = { "DiagnosticError", "fg" },
		[2] = { "DiagnosticOk", "fg" },
		[3] = { "DiagnosticWarn", "fg" },
		[4] = { "DiagnosticInfo", "fg" },
		[5] = { "Statement", "fg" },
		[6] = { "Special", "fg" },
		[7] = { "Normal", "fg" },
	}

	for i = 0, 7 do
		local term_hl = api.nvim_get_hl(0, { name = "Terminal" .. i, link = false })
		if term_hl.fg then
			colors["color" .. i] = string.format("#%06X", term_hl.fg)
		else
			local map = term_map[i]
			colors["color" .. i] = hl_hex(map[1], map[2])
		end

		local bright_hl = api.nvim_get_hl(0, { name = "Terminal" .. (i + 8), link = false })
		if bright_hl.fg then
			colors["color" .. (i + 8)] = string.format("#%06X", bright_hl.fg)
		else
			colors["color" .. (i + 8)] = colors["color" .. i]
		end
	end

	return colors
end

--- Write colors to a Kitty conf file and reload Kitty via SIGUSR1.
local function sync_to_kitty()
	local colors = get_nvim_colors()

	local lines = { "# Auto-generated by Chameleon.nvim — do not edit" }
	for name, hex in pairs(colors) do
		if hex then
			table.insert(lines, string.format("%-24s %s", name, hex))
		end
	end

	-- Write the theme file
	local f = io.open(conf_path, "w")
	if not f then
		vim.notify("Chameleon.nvim: Cannot write " .. conf_path, vim.log.levels.ERROR)
		return
	end
	f:write(table.concat(lines, "\n") .. "\n")
	f:close()

	-- Reload Kitty config via SIGUSR1
	local pid = vim.env.KITTY_PID
	if pid then
		os.execute("kill -SIGUSR1 " .. pid)
	end
end

local function setup_autocmds()
	local group = api.nvim_create_augroup("ChameleonSync", { clear = true })

	api.nvim_create_autocmd({ "ColorScheme", "VimResume", "VimEnter" }, {
		pattern = "*",
		callback = sync_to_kitty,
		group = group,
	})
end

M.setup = function()
	if not vim.env.KITTY_PID then
		return
	end
	setup_autocmds()
end

return M
